[package]
name = "v4l-sys"
version = "0.1.0"
authors = ["Christopher N. Hesse <raymanfx@gmail.com>"]
edition = "2018"
license = "MIT"
links = "v4l1 v4l2 4lconvert"
build = "build.rs"

[build-dependencies]
bindgen = "0.53.2"
