[package]
name = "v4l2-sys"
description = "Raw v4l2 bindings"
version = "0.1.0"
authors = ["Christopher N. Hesse <raymanfx@gmail.com>"]
edition = "2018"
license = "MIT"
build = "build.rs"

[build-dependencies]
bindgen = "0.53.2"
